Repository Azure/azure-monitor-baseline-alerts, pull requests merged in 2023-10, with the labels that each got.

#33 Bugfix - parameter path in workflow
  patterns/alz/examples/sample-workflow.yml
Labels: bug

#34 Documenting how to modify individual policies
  docs/content/contributing/_index.md
  docs/content/patterns/alz/Alerts-Details.md
  docs/content/patterns/alz/deploy/Customize-Policy-Assignment.md
  docs/content/patterns/alz/deploy/Deploy-with-Azure-CLI.md
  docs/content/patterns/alz/deploy/Deploy-with-Azure-Pipelines.md
  docs/content/patterns/alz/deploy/Deploy-with-Azure-PowerShell.md
  docs/content/patterns/alz/deploy/Deploy-with-GitHub-Actions.md
  docs/content/patterns/alz/deploy/Introduction-to-deploying-the-ALZ-Pattern.md
Labels: documentation

#45 AMBA Service Health Granular Deployment Flexibility
  patterns/alz/alzArm.param.json
  patterns/alz/policyDefinitions/policies.json
  patterns/alz/policySetDefinitions/Deploy-ServiceHealth-Alerts.json
  services/Resources/subscriptions/Deploy-ActivityLog-ResourceHealth-UnHealthly-Alert.json
  services/Resources/subscriptions/Deploy-ActivityLog-ServiceHealth-Health.json
  services/Resources/subscriptions/Deploy-ActivityLog-ServiceHealth-Incident.json
  services/Resources/subscriptions/Deploy-ActivityLog-ServiceHealth-Maintenance.json
  services/Resources/subscriptions/Deploy-ActivityLog-ServiceHealth-Security.json
Labels: enhancement

#44 Bug 42 (31506) role assignment cleanup
  patterns/alz/scripts/Start-ALZMonitorCleanup.ps1
  patterns/alz/scripts/Start-AMBACleanup.ps1
Labels: bug

#40 Update alzMetricAlerts.html - Fixed spelling of Resources
  docs/layouts/shortcodes/alzMetricAlerts.html
Labels: documentation

#55 Added guide to only deploy service health
  docs/content/patterns/alz/deploy/Deploy-only-Service-Health-Alerts.md
  docs/content/patterns/alz/deploy/Remediate-Policies.md
Labels: documentation
