Repository Azure/azure-monitor-baseline-alerts, pull requests merged in 2023-11, with the labels that each got.

#63 FAQ Update
  docs/content/patterns/alz/FAQ.md
Labels: documentation

#57 Lz2alerts
  patterns/alz/alzArm.param.json
  patterns/alz/policyDefinitions/policies.json
  patterns/alz/policySetDefinitions/Deploy-LandingZone-Alerts.json
  patterns/alz/templates/policies.bicep
  services/Cdn/profiles/Deploy-CDNP-OriginHealthPercentage-Alert.json
  services/Cdn/profiles/Deploy-CDNP-OriginLatency-Alert.json
  services/Cdn/profiles/Deploy-CDNP-Percentage4XX-Alert.json
  services/Cdn/profiles/Deploy-CDNP-Percentage5XX-Alert.json
  services/Network/frontdoors/Deploy-FD-BackendHealth-Alert.json
  services/Network/frontdoors/Deploy-FD-BackendRequestLatency-Alert.json
  services/Network/trafficmanagerprofiles/Deploy-TM-EndpointHealth-Alert.json
  services/Web/serverFarms/Deploy-WSF-CPUPercentage-Alert.json
  services/Web/serverFarms/Deploy-WSF-DiskQueueLength-Alert.json
  services/Web/serverFarms/Deploy-WSF-HttpQueueLength-Alert.json
  services/Web/serverFarms/Deploy-WSF-MemoryPercentage-Alert.json
Labels: enhancement

#71 Update to new release guidance
  docs/content/contributing/_index.md
  docs/content/patterns/alz/FAQ.md
  docs/content/patterns/alz/Update-to-new-Release.md
  docs/content/patterns/alz/Whats-New.md
  docs/content/patterns/alz/media/BranchUpToDate.png
  docs/content/patterns/alz/media/ConfirmPull.png
  docs/content/patterns/alz/media/GitHub_Code.png
  docs/content/patterns/alz/media/PullCompleted.png
  docs/content/patterns/alz/media/PullIcon.png
  docs/content/patterns/alz/media/Releases.png
  docs/content/patterns/alz/media/UpdateBranch.png
Labels: documentation

#74 Release 2023-11-14
  docs/content/patterns/alz/Whats-New.md
Labels: documentation

#79 Change to forward slashes
  patterns/alz/examples/sample-pipeline.yml
Labels: bug
