Repository Azure/azure-monitor-baseline-alerts, pull requests merged in 2025-04, with the labels that each got.

#571 Update alert rules for Cosmos DB
  services/DocumentDB/databaseAccounts/alerts.yaml
Labels: AMBA Core

#587 Feat assign permissions
  patterns/alz/policyDefinitions/policies-Compute.json
  patterns/alz/policyDefinitions/policies-Hybrid.json
  services/Compute/virtualMachines/Deploy-VM-DataDiskReadLatency-Alert.json
  services/Compute/virtualMachines/Deploy-VM-DataDiskSpace-Alert.json
  services/Compute/virtualMachines/Deploy-VM-DataDiskWriteLatency-Alert.json
  services/Compute/virtualMachines/Deploy-VM-HeartBeat-Alert.json
  services/Compute/virtualMachines/Deploy-VM-NetworkIn-Alert.json
  services/Compute/virtualMachines/Deploy-VM-NetworkOut-Alert.json
  services/Compute/virtualMachines/Deploy-VM-OSDiskReadLatency-Alert.json
  services/Compute/virtualMachines/Deploy-VM-OSDiskSpace-Alert.json
  services/Compute/virtualMachines/Deploy-VM-OSDiskWriteLatency-Alert.json
  services/Compute/virtualMachines/Deploy-VM-PercentCPU-Alert.json
  services/Compute/virtualMachines/Deploy-VM-PercentMemory-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-DataDiskReadLatency-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-DataDiskSpace-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-DataDiskWriteLatency-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-Disconnected-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-HeartBeat-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-NetworkIn-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-NetworkOut-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-OSDiskReadLatency-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-OSDiskSpace-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-OSDiskWriteLatency-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-PercentCPU-Alert.json
  services/HybridCompute/machines/Deploy-Hybrid-VM-PercentMemory-Alert.json
Labels: Area: Policy :pencil:, Pattern: ALZ :helicopter:

#582 Tooling
  .editorconfig
  .github/actions-pester/PolicyPesterTestHelper.psm1
  .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
Labels: Pattern: ALZ :helicopter:

#589 Adding JPG version of AMBA logo
  docs/static/img/amba_logo.jpg
Labels: AMBA Core

#579 feat: terraform deployment documentation
  docs/content/patterns/alz/HowTo/deploy/Deploy-with-Terraform.md
Labels: documentation, Pattern: ALZ :helicopter:

#603 fix: AMBA - Diagrams.vsdx download link invalid
  docs/content/patterns/alz/HowTo/deploy/Introduction-to-deploying-the-ALZ-Pattern.md
Labels: Pattern: ALZ :helicopter:

#604 Update alerts.yaml
  services/DocumentDB/databaseAccounts/alerts.yaml
Labels: AMBA Core

#605 PG Verified alert updates for Disks
  services/Compute/virtualMachines/alerts.yaml
Labels: AMBA Core

#608 Tooling
  .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
Labels: Pattern: ALZ :helicopter:

#609 fix: refine filtering for modified and added policy files in tests
  .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
Labels: Pattern: ALZ :helicopter:

#611 Tooling
  .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
Labels: Pattern: ALZ :helicopter:
